apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: a1m1
  name: a1m1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a1m1
  strategy: {}
  template:
    metadata:
      labels:
        app: a1m1
        appgraph: a1
    spec:
      containers:
      - image: dsantoro/ubuntu
        name: ubuntu
        command:
        - "/bin/sh"
        - "-ecx"
        - |
          echo "I am pod: $MY_POD_NAME runing on node: $MY_NODE_NAME" | tee index.html
          python -m http.server 8000 2>&1
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources: {}
        ports:
        - containerPort: 8000
status: {}
