apiVersion: nodecore.fluidos.eu/v1alpha1
kind: Flavor
metadata:
  name: fluidos.eu-k8slice-2f1640fd4dfb151b4d81ad9590dcb6cc
  ownerReferences:
  - apiVersion: nodecore.fluidos.eu/v1alpha1
    kind: Node
    name: fluidos-consumer-1-worker
    uid: bcbc5b65-3de6-434a-aef9-a329317a189d
  resourceVersion: "1956"
  uid: 1dbd9361-a36b-4ee6-adff-958b5e0647bf
spec:
  availability: true
  flavorType:
    typeData:
      characteristics:
        architecture: amd64
        cpu: 1947481697n
        gpu:
          cores: "0"
          memory: "0"
          model: ""
        memory: 3735836Ki
        pods: "110"
        storage: "0"
      policies:
        partitionability:
          cpuMin: "0"
          cpuStep: "1"
          gpuMin: "0"
          gpuStep: "0"
          memoryMin: "0"
          memoryStep: 100Mi
          podsMin: "0"
          podsStep: "0"
      properties: {}
    typeIdentifier: K8Slice
  location:
    additionalNotes: None
    city: Turin
    country: Italy
    latitude: "10"
    longitude: "58"
  networkPropertyType: networkProperty
  owner:
    domain: fluidos.eu
    ip: 172.18.0.7:30000
    nodeID: ekvjnuvsel
  price:
    amount: ""
    currency: ""
    period: ""
  providerID: ekvjnuvsel
