apiVersion: fluidos.eu/v1
kind: FLUIDOSDeployment
metadata:
  name: www-cd-pod
spec:
  apiVersion: v1
  kind: Pod
  metadata:
    name: www-cd
    annotations:
      fluidos-intent-cyber-deception: "true"
    labels:
      app: www
  spec:
    containers:
      - name: www
        image: nginx:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"