apiVersion: fluidos.eu/v1
kind: FLUIDOSDeployment
metadata:
  name: www-cd-deploy
spec:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: www-cd
    annotations:
      fluidos-intent-cyber-deception: "true"
    labels:
      app: www
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: www
    template:
      metadata:
        labels:
          app: www
      spec:
        containers:
          - name: www
            image: nginx:latest
            ports:
              - containerPort: 80
            resources:
              requests:
                memory: "64Mi"
                cpu: "100m"
              limits:
                memory: "128Mi"
                cpu: "250m"